<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="BCrypt.Net-Next" Version="4.0.3" />
    <PackageReference Include="Pomelo.EntityFrameworkCore.MySql" Version="8.0.2" />
  </ItemGroup>

  <ItemGroup>
    <Compile Include="..\DineSmart.Core\**\*.cs" LinkBase="DineSmart.Core" />
    <Compile Include="..\DineSmart.Data\**\*.cs" LinkBase="DineSmart.Data" />
    <Compile Include="..\DineSmart.Services\**\*.cs" LinkBase="DineSmart.Services" />
  </ItemGroup>

</Project>
